/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
	,
    {
      type: 'category',
      label: '基础组件',
	  link: {
        type: 'generated-index' // 添加此参数可以在点击这个 label 的时候有一个概览的界面
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'flutter'
        }
      ]
	},
//	{
//      type: 'category',
//      label: '布局组件',
//      collapsed: true,
//      items: [
//        'layout/box',
//        'layout/row',
//      ]
//    },
  ]
};

module.exports = sidebars;
